# Generated by Django 5.2.12 on 2026-03-22 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.FloatField(default=1, verbose_name='Альфа')),
                ('beta', models.FloatField(default=1, verbose_name='Бета')),
                ('gamma', models.FloatField(default=1, verbose_name='Гамма')),
                ('h', models.FloatField(default=9, verbose_name='H')),
                ('n', models.FloatField(default=10, verbose_name='N')),
                ('l_min', models.FloatField(default=1, verbose_name='Нижняя граница L')),
                ('l_max', models.FloatField(default=15, verbose_name='Верхняя граница L')),
                ('s_min', models.FloatField(default=1, verbose_name='Нижняя граница S')),
                ('s_max', models.FloatField(default=12, verbose_name='Верхняя граница S')),
                ('sum_constraint', models.FloatField(default=12, verbose_name='Граница суммы L + S')),
                ('computation_model', models.CharField(choices=[('gradient', 'Градиентный метод')], default='gradient', max_length=255, verbose_name='Метод оптимизации')),
                ('l_result', models.FloatField(null=True, verbose_name='Рассчитанный L')),
                ('s_result', models.FloatField(null=True, verbose_name='Рассчитанный S')),
                ('values', models.JSONField(null=True, verbose_name='Значения')),
                ('history', models.JSONField(null=True, verbose_name='История')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат оптимизации',
                'verbose_name_plural': 'Результат оптимизации',
            },
        ),
    ]
